name: criticalcare
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.1
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  font_awesome_flutter: ^8.4.0
  formz: ^0.2.0
  google_fonts: ^1.1.0
  meta: ^1.1.8
  pedantic: ^1.9.0
  authentication_repository:
    path: packages/authentication_repository
  hospital_repository:
    path: packages/hospital_repository
  patient_repository:
    path: packages/patient_repository
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  charts_flutter: ^0.9.0
  enum_to_string: ^ 1.0.9
  oscilloscope: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.0
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: DIN-Bold
      fonts:
        - asset: fonts/DINAlternateBold.ttf
    - family: Varela Round
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
    - family: Verdana
      fonts:
        - asset: fonts/verdana.ttf
