name: criticalcare
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.1
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  font_awesome_flutter: ^8.4.0
  formz: ^0.2.0
  google_fonts: ^1.1.0
  meta: ^1.1.8
  pedantic: ^1.9.0
  authentication_repository:
    path: packages/authentication_repository
  hospital_repository:
    path: packages/hospital_repository
  patient_repository:
    path: packages/patient_repository
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  charts_flutter: ^0.9.0
  enum_to_string: ^ 1.0.9
  url_launcher: ^5.1.3
  permission_handler: ^3.2.0
  mp_chart: ^0.2.2
  qrscan: ^0.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.0
  mockito: ^4.0.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/fonts/
    - assets/graphs/

  fonts:
    - family: DIN-Bold
      fonts:
        - asset: assets/fonts/DINAlternateBold.ttf
    - family: Varela Round
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Verdana
      fonts:
        - asset: assets/fonts/verdana.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiboldItalic.ttf
          weight: 600
          style: italic
