name: hospital_repository
description: Dart package which manages the hospital domain.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  hospital_api_client:
    path: ../hospital_api_client